/**
 * ARIA - token CSS generator
 *
 * Reads src/design/tokens.ts and writes src/app/tokens.css. Run by `prebuild`
 * and `predev`, so the CSS custom properties, the Tailwind theme, the viewport
 * theme-color and the manifest can never disagree.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const src = fs.readFileSync(path.join(root, 'src/design/tokens.ts'), 'utf8')

// Tiny extractor: the token maps are plain literals, so parse them rather than
// pulling in a TS toolchain for a build step that runs before every build.
function parseMap(name) {
  const m = src.match(new RegExp(`export const ${name}: Record<TokenName, Triplet> = \\{([\\s\\S]*?)\\n\\}`))
  if (!m) throw new Error(`token map ${name} not found`)
  const out = {}
  for (const line of m[1].split('\n')) {
    const t = line.match(/'?([a-z0-9-]+)'?:\s*\[(\d+),\s*(\d+),\s*(\d+)\]/i)
    if (t) out[t[1]] = `${t[2]} ${t[3]} ${t[4]}`
  }
  return out
}

const dark = parseMap('dark')
const light = parseMap('light')
const names = Object.keys(light)
if (names.length !== Object.keys(dark).length) throw new Error('theme token sets differ')

const decl = (map, indent = '  ') =>
  names.map((n) => `${indent}--${n}-rgb: ${map[n]};`).join('\n')

const css = `/* GENERATED by scripts/gen-tokens.mjs from src/design/tokens.ts — do not edit. */

/*
  Light is the bare :root palette; dark is redefined in BOTH a
  prefers-color-scheme block (guarded so an explicit light choice wins) and a
  [data-theme="dark"] block (so the toggle wins in the other direction). Every
  component reads the token, never a literal, so no component branches on theme.
*/
:root {
  color-scheme: light dark;
${decl(light)}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
    color-scheme: dark;
${decl(dark, '    ')}
  }
}

:root[data-theme='dark'] {
  color-scheme: dark;
${decl(dark)}
}

:root[data-theme='light'] {
  color-scheme: light;
${decl(light)}
}
`
fs.writeFileSync(path.join(root, 'src/app/tokens.css'), css)
console.log(`tokens.css: ${names.length} tokens x 2 themes`)
