"""
ARIA - Model Pull & Runtime Provisioning

Purpose: Pull a GGUF from Hugging Face into the shared models directory
(infrastructure/models/llm/<name>/), generate a docker-compose service for it
on a chosen runtime, and register it as a DYNAMIC model-server registry entry
(db.model_servers) that the ModelServerManager control plane can start/stop
exactly like the static entries.

Runtime choice matters on this box (see model_servers.py): a standard GGUF
runs on mainline llama.cpp, but ROCmFP4/ROCmFPX-quantized files need their
matching fork image. The templates below only reference images that already
exist on this box (verified 2026-07-29) — provisioning never builds an image.

Jobs are tracked in db.model_pulls and driven by an in-process asyncio task:
if aria-api restarts mid-download, the job doc stays at its last phase with
no worker behind it — surfaced as `stale: true` in the listing rather than
silently pretending to progress.
"""

from __future__ import annotations

import asyncio
import logging
import os
import re
from datetime import datetime, timezone
from typing import Optional

from bson import ObjectId
from motor.motor_asyncio import AsyncIOMotorDatabase

from aria.config import settings
from aria.infrastructure.model_servers import REGISTRY, ModelServerError

logger = logging.getLogger(__name__)

_SLUG_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{1,62}$")
_REPO_RE = re.compile(r"^[A-Za-z0-9][\w.-]*/[\w.-]+$")
# Ports below 8105 belong to existing services (see endpoints.env / the static
# registry); generated services allocate upward from here.
_PORT_RANGE = range(8105, 8130)
_TAILNET_IP = "100.123.245.84"  # this node's stable Tailscale IP, same as every other compose file


# Each template only uses images already present on this box. `entrypoint`
# None means the image's own entrypoint already is llama-server (mainline
# images); otherwise the fork's build output path.
RUNTIME_TEMPLATES: dict[str, dict] = {
    "mainline-vulkan": {
        "description": "mainline llama.cpp, Vulkan GPU (standard GGUFs, GPU-offloaded)",
        "image": "ghcr.io/ggml-org/llama.cpp:server-vulkan",
        "entrypoint": None,
        "gpu": "vulkan",
        "ngl": "999",
        "extra_env": [],
    },
    "mainline-cpu": {
        "description": "mainline llama.cpp, CPU only (standard GGUFs, no GPU contention)",
        "image": "ghcr.io/ggml-org/llama.cpp:server",
        "entrypoint": None,
        "gpu": None,
        "ngl": "0",
        "extra_env": [],
    },
    "rocmfp4-fork": {
        "description": "charlie12345/ROCmFPX fork (ROCmFP4/FP6 tensor types), served on Vulkan0",
        "image": "qwen-rocmfp4:latest",
        "entrypoint": "/opt/rocmfp4/build-strix-rocmfp4/bin/llama-server",
        "gpu": "vulkan",
        "ngl": "999",
        "extra_env": ["HSA_OVERRIDE_GFX_VERSION=11.5.1", "GGML_HIP_ENABLE_UNIFIED_MEMORY=1"],
    },
    "rocmfpx-vulkan-fork": {
        "description": "ciru-ai/ROCmFPX fork @090e317b (laguna arch + ROCmFP4 types), Vulkan/RADV",
        "image": "chadrock-rocmfpx:latest",
        "entrypoint": "/opt/rocmfpx/build-laguna-strix-vulkan/bin/llama-server",
        "gpu": "vulkan",
        "ngl": "999",
        "extra_env": [],
    },
}


def _compose_yaml(slug: str, runtime: str, model_filename: str, port: int, ctx: int) -> str:
    t = RUNTIME_TEMPLATES[runtime]
    lines: list[str] = []
    lines.append(f"# Auto-generated by ARIA model-pull on {datetime.now(timezone.utc).date()}.")
    lines.append(f"# Runtime template: {runtime} — {t['description']}")
    lines.append("# Managed by ARIA's model-server control plane; edit and `start` to apply")
    lines.append("# (compose-managed containers are reconciled via `docker compose up -d`).")
    lines.append("services:")
    lines.append(f"  {slug}:")
    lines.append(f"    image: {t['image']}")
    lines.append(f"    container_name: {slug}")
    lines.append(f"    hostname: {slug}")
    lines.append('    restart: "no"')
    lines.append("    logging:")
    lines.append("      driver: json-file")
    lines.append('      options: {max-size: "50m", max-file: "3"}')
    lines.append("    ports:")
    lines.append(f'      - "127.0.0.1:{port}:8080"')
    lines.append(f'      - "{_TAILNET_IP}:{port}:8080"')
    if t["extra_env"]:
        lines.append("    environment:")
        for env in t["extra_env"]:
            lines.append(f"      - {env}")
    if t["entrypoint"]:
        lines.append("    entrypoint:")
        lines.append(f"      - {t['entrypoint']}")
    lines.append("    command:")
    for arg in (
        "-m", f"/models/{model_filename}",
        "--alias", slug,
        "--host", "0.0.0.0",
        "--port", "8080",
        "-c", str(ctx),
        "-ngl", t["ngl"],
        "--jinja",
        "--metrics",
    ):
        lines.append(f'      - "{arg}"')
    lines.append("    volumes:")
    lines.append(f"      - {os.path.join(settings.infrastructure_root, 'models/llm', slug)}:/models:ro")
    if t["gpu"] == "vulkan":
        lines.append("    devices:")
        lines.append("      - /dev/dri:/dev/dri")
        lines.append("    group_add:")
        lines.append('      - "44"   # video')
        lines.append('      - "992"  # render')
        lines.append("    security_opt:")
        lines.append("      - seccomp:unconfined")
    lines.append("    networks:")
    lines.append("      - shared-infra")
    lines.append("networks:")
    lines.append("  shared-infra:")
    lines.append("    external: true")
    lines.append("")
    return "\n".join(lines)


class ModelPullService:
    """Download + provision pipeline. One in-flight pull at a time — these
    are 20-60 GB files on one disk; parallel pulls just thrash."""

    def __init__(self):
        self.infrastructure_root = os.path.abspath(settings.infrastructure_root)
        self._active_task: Optional[asyncio.Task] = None

    # ── validation ──────────────────────────────────────────────────────

    async def _validate(
        self, db: AsyncIOMotorDatabase, repo_id: str, filename: str, name: str,
        runtime: str, port: Optional[int],
    ) -> int:
        if not _REPO_RE.match(repo_id):
            raise ModelServerError(f"Invalid Hugging Face repo id: {repo_id!r} (expected org/repo)")
        if not filename.endswith(".gguf") or "/" in filename or filename.startswith("."):
            raise ModelServerError(f"Invalid GGUF filename: {filename!r}")
        if not _SLUG_RE.match(name):
            raise ModelServerError(
                f"Invalid name: {name!r} (letters/digits/dot/dash/underscore, no spaces)"
            )
        if runtime not in RUNTIME_TEMPLATES:
            raise ModelServerError(
                f"Unknown runtime {runtime!r}; choose from {sorted(RUNTIME_TEMPLATES)}"
            )
        static_slugs = {s.slug for s in REGISTRY}
        if name in static_slugs or await db.model_servers.find_one({"slug": name}):
            raise ModelServerError(f"A model server named {name!r} already exists")
        if self._active_task and not self._active_task.done():
            raise ModelServerError("Another pull is already in progress — one at a time")

        used_ports = {s.port for s in REGISTRY if s.port}
        async for doc in db.model_servers.find({}):
            if doc.get("port"):
                used_ports.add(doc["port"])
        if port is not None:
            if port in used_ports:
                raise ModelServerError(f"Port {port} is already assigned to another server")
            return port
        for candidate in _PORT_RANGE:
            if candidate not in used_ports:
                return candidate
        raise ModelServerError("No free port left in the generated range (8105-8129)")

    # ── public API ──────────────────────────────────────────────────────

    async def start_pull(
        self, db: AsyncIOMotorDatabase, repo_id: str, filename: str, name: str,
        runtime: str, port: Optional[int] = None, ctx: int = 32768,
    ) -> dict:
        resolved_port = await self._validate(db, repo_id, filename, name, runtime, port)
        now = datetime.now(timezone.utc)
        job = {
            "slug": name,
            "repo_id": repo_id,
            "filename": filename,
            "runtime": runtime,
            "port": resolved_port,
            "ctx": ctx,
            "status": "downloading",
            "error": None,
            "log_tail": "",
            "started_at": now,
            "finished_at": None,
        }
        result = await db.model_pulls.insert_one(job)
        job_id = result.inserted_id
        self._active_task = asyncio.create_task(
            self._run_job(db, job_id, repo_id, filename, name, runtime, resolved_port, ctx)
        )
        return {"job_id": str(job_id), "slug": name, "port": resolved_port, "status": "downloading"}

    async def list_jobs(self, db: AsyncIOMotorDatabase, limit: int = 20) -> list[dict]:
        jobs = []
        active = self._active_task is not None and not self._active_task.done()
        cursor = db.model_pulls.find({}).sort("started_at", -1).limit(limit)
        async for doc in cursor:
            doc["job_id"] = str(doc.pop("_id"))
            # A non-terminal job with no live worker means aria-api restarted
            # mid-pull — dead, not in progress.
            doc["stale"] = doc["status"] in ("downloading", "wiring") and not active
            jobs.append(doc)
        return jobs

    # ── the job ─────────────────────────────────────────────────────────

    async def _run_job(
        self, db: AsyncIOMotorDatabase, job_id: ObjectId, repo_id: str, filename: str,
        name: str, runtime: str, port: int, ctx: int,
    ) -> None:
        target_dir = os.path.join(self.infrastructure_root, "models", "llm", name)
        try:
            os.makedirs(target_dir, exist_ok=True)
            # Positional filename, NOT --include: --include has silently
            # skipped large files before (see agent-memory note from the
            # Chadrockv2 download session).
            proc = await asyncio.create_subprocess_exec(
                "hf", "download", repo_id, filename, "--local-dir", target_dir,
                stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.STDOUT,
            )
            tail: list[bytes] = []
            assert proc.stdout is not None
            async for line in proc.stdout:
                tail.append(line[-500:])
                tail = tail[-10:]
                await db.model_pulls.update_one(
                    {"_id": job_id},
                    {"$set": {"log_tail": b"".join(tail).decode("utf-8", "replace")[-2000:]}},
                )
            rc = await proc.wait()
            if rc != 0:
                raise ModelServerError(f"hf download exited {rc}")

            model_path = os.path.join(target_dir, filename)
            if not os.path.isfile(model_path):
                raise ModelServerError(f"Download reported success but {filename} is missing")
            size_gib = os.path.getsize(model_path) / 1024**3

            await db.model_pulls.update_one({"_id": job_id}, {"$set": {"status": "wiring"}})

            compose_dir = os.path.join(self.infrastructure_root, "generated", name)
            os.makedirs(compose_dir, exist_ok=True)
            compose_path = os.path.join(compose_dir, "docker-compose.yml")
            with open(compose_path, "w", encoding="utf-8") as f:
                f.write(_compose_yaml(name, runtime, filename, port, ctx))

            t = RUNTIME_TEMPLATES[runtime]
            await db.model_servers.insert_one({
                "slug": name,
                "description": f"Pulled from hf.co/{repo_id} on "
                f"{datetime.now(timezone.utc).date()} ({runtime} runtime).",
                "runtime_repo": t["image"],
                "runtime_ref": f"template {runtime} — {t['description']}",
                "backend_device": "Vulkan0" if t["gpu"] == "vulkan" else "CPU only",
                "model_file": f"models/llm/{name}/{filename}",
                "port": port,
                "compose_file": f"generated/{name}/docker-compose.yml",
                "service_name": name,
                "container_name": name,
                "profile": None,
                # SWAG: weights + KV/compute overhead. Same spirit as the
                # static entries — a gate input, not a measurement.
                "resident_gib": round(size_gib * 1.15 + 4, 1),
                "gtt_resident": t["gpu"] == "vulkan",
                "source_repo": repo_id,
                "created_at": datetime.now(timezone.utc),
            })
            await db.model_pulls.update_one(
                {"_id": job_id},
                {"$set": {"status": "completed", "finished_at": datetime.now(timezone.utc),
                          "size_gib": round(size_gib, 2)}},
            )
            logger.info("model_pull: %s provisioned on :%d (%s, %.1f GiB)", name, port, runtime, size_gib)
        except Exception as exc:
            logger.exception("model_pull: job for %s failed", name)
            await db.model_pulls.update_one(
                {"_id": job_id},
                {"$set": {"status": "failed", "error": str(exc)[:500],
                          "finished_at": datetime.now(timezone.utc)}},
            )
